"""Shared strict immutable value objects for the event-sourced core."""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Annotated, Literal

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StringConstraints,
    field_validator,
    model_validator,
)

Identifier = Annotated[
    str,
    StringConstraints(min_length=1, max_length=240, pattern=r"^[A-Za-z0-9][A-Za-z0-9._:/-]*$"),
]
Sha256Digest = Annotated[str, StringConstraints(pattern=r"^[0-9a-f]{64}$")]
NonEmptyText = Annotated[str, StringConstraints(min_length=1, max_length=4096)]


class FrozenModel(BaseModel):
    """Base for records whose fields and nested containers are immutable."""

    model_config = ConfigDict(
        allow_inf_nan=False,
        extra="forbid",
        frozen=True,
        strict=True,
        validate_default=True,
    )


def require_utc(value: datetime) -> datetime:
    """Reject naive or non-UTC values so serialized event time is canonical."""

    if value.tzinfo is None or value.utcoffset() != timedelta(0):
        raise ValueError("timestamps must be timezone-aware UTC values")
    return value


class ArtifactRef(FrozenModel):
    """A reference to exact bytes in a SHA-256 content-addressed store."""

    algorithm: Literal["sha256"] = "sha256"
    digest: Sha256Digest
    size: Annotated[int, Field(ge=0)]
    media_type: NonEmptyText | None = None
    encoding: NonEmptyText | None = None


class CapturedPayload(FrozenModel):
    """Distinguish a captured native null from captured byte material."""

    kind: Literal["bytes", "null"]
    artifact: ArtifactRef | None = None

    @model_validator(mode="after")
    def validate_payload_shape(self) -> CapturedPayload:
        if (self.kind == "bytes") != (self.artifact is not None):
            raise ValueError("byte payloads require an artifact and null payloads forbid one")
        return self


class EventMetadata(FrozenModel):
    """Nondeterministic event facts supplied to, never generated by, reducers."""

    event_id: Identifier
    inquiry_id: Identifier
    occurred_at: datetime

    _validate_occurred_at = field_validator("occurred_at")(require_utc)


class InquiryContext(FrozenModel):
    """Replay-complete semantic pins for one inquiry binding and local scope."""

    binding_revision: Identifier
    carrier_schema_ids: tuple[Identifier, ...]
    relation_schema_ids: tuple[Identifier, ...]
    consequence_profile_id: Identifier
    protected_horizon_id: Identifier
    admissible_operation_ids: tuple[Identifier, ...] = ()
    discharge_mechanism_ids: tuple[Identifier, ...] = ()
    scope_id: Identifier
    scope_fingerprint: Sha256Digest
    assumption_ids: tuple[Identifier, ...] = ()
    guard_condition_id: Identifier | None = None
    guard_ast: ArtifactRef | None = None
    finite_universe_hash: Sha256Digest | None = None
    closed_world: bool = False
    catalog_manifest_digest: Sha256Digest
    scheduler_policy_version: Identifier
    warrant_policy_version: Identifier
    provenance_refs: tuple[Identifier, ...]

    @model_validator(mode="after")
    def validate_context(self) -> InquiryContext:
        if not self.carrier_schema_ids or not self.relation_schema_ids:
            raise ValueError("an inquiry must pin typed carrier and relation schemas")
        if not self.provenance_refs:
            raise ValueError("an inquiry must pin at least one provenance reference")
        for collection in (
            self.carrier_schema_ids,
            self.relation_schema_ids,
            self.admissible_operation_ids,
            self.discharge_mechanism_ids,
            self.assumption_ids,
            self.provenance_refs,
        ):
            if len(set(collection)) != len(collection):
                raise ValueError("inquiry context reference collections must be unique")
        if self.closed_world and self.finite_universe_hash is None:
            raise ValueError("closed-world inquiry contexts require a finite-universe hash")
        if (self.guard_condition_id is None) != (self.guard_ast is None):
            raise ValueError("guard identity and guard AST artifact must be pinned together")
        return self
