"""G3A-H exact history-state contracts and reference fixtures."""

from rci.compression.fixtures import (
    ExactFixtureResult,
    ExactFixtureVerdict,
    FiniteTransitionPresentation,
    validate_finite_transition_quotient,
    validate_order_sensitive_count,
    validate_present_answer_without_continuation,
    validate_unary_parity,
)
from rci.compression.models import (
    BindingCarrierManifest,
    CarrierContract,
    CarrierRole,
    CompressionApplication,
    CompressionContract,
    CompressionValidation,
    ExactClaimKind,
    ExactCompressionLicense,
    ExactPropertyValidation,
    HistoryDerivationStatus,
    PathResidue,
    RealizedHistoryDerivation,
    RecoveryLicense,
    ReopeningOutcome,
    RepresentationGainKind,
    RepresentationReopening,
    RepresentationSuccessorDecision,
    RetainedStateView,
    RetentionCapabilityLink,
    SuccessorDisposition,
    ValidationOutcome,
    ValidationProperty,
)

__all__ = [
    "BindingCarrierManifest",
    "CarrierContract",
    "CarrierRole",
    "CompressionApplication",
    "CompressionContract",
    "CompressionValidation",
    "ExactClaimKind",
    "ExactCompressionLicense",
    "ExactFixtureResult",
    "ExactFixtureVerdict",
    "ExactPropertyValidation",
    "FiniteTransitionPresentation",
    "HistoryDerivationStatus",
    "PathResidue",
    "RealizedHistoryDerivation",
    "RecoveryLicense",
    "ReopeningOutcome",
    "RepresentationGainKind",
    "RepresentationReopening",
    "RepresentationSuccessorDecision",
    "RetainedStateView",
    "RetentionCapabilityLink",
    "SuccessorDisposition",
    "ValidationOutcome",
    "ValidationProperty",
    "validate_finite_transition_quotient",
    "validate_order_sensitive_count",
    "validate_present_answer_without_continuation",
    "validate_unary_parity",
]
